{
	"version":"LAYASCENE3D:02",
	"data":{
		"type":"Scene3D",
		"props":{
			"name":"jump",
			"ambientColor":[
				0.212,
				0.227,
				0.259
			],
			"reflectionDecodingFormat":1,
			"reflection":"Assets/Scenes/jump/jumpGIReflection.ltcb.ls",
			"reflectionIntensity":1,
			"ambientMode":1,
			"ambientSphericalHarmonics":[
				0.1670712,
				-0.01669491,
				-0.003398944,
				0.01236076,
				0.009396347,
				-0.002583353,
				0.00582308,
				-0.005357776,
				0.0263654,
				0.2096689,
				0.02698341,
				-0.005640998,
				0.02051617,
				0.01587153,
				-0.004363231,
				0.008184383,
				-0.008190211,
				0.03818536,
				0.2891939,
				0.1104058,
				-0.01041667,
				0.03787509,
				0.03079787,
				-0.008469004,
				0.009074805,
				-0.0124048,
				0.04797072
			],
			"ambientSphericalHarmonicsIntensity":1,
			"lightmaps":[],
			"enableFog":false,
			"fogStart":0,
			"fogRange":300,
			"fogColor":[
				0.5,
				0.5,
				0.5
			]
		},
		"child":[
			{
				"type":"DirectionLight",
				"instanceID":0,
				"props":{
					"name":"Directional Light",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						55.5,
						0
					],
					"rotation":[
						-0.09950887,
						0.7617445,
						0.6135444,
						-0.1827747
					],
					"scale":[
						1,
						1,
						1
					],
					"intensity":1,
					"lightmapBakedType":0,
					"color":[
						1,
						0.9302385,
						0.8066038
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":1,
				"props":{
					"name":"player_Game",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						0,
						-99.3
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[
					{
						"type":"Sprite3D",
						"instanceID":2,
						"props":{
							"name":"Camer_Game",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"Camera",
								"instanceID":3,
								"props":{
									"name":"Camera",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										-282.6,
										557.7,
										-321.4
									],
									"rotation":[
										0.1516873,
										0.8349062,
										0.4176848,
										-0.3247491
									],
									"scale":[
										1,
										1,
										1
									],
									"clearFlag":1,
									"orthographic":false,
									"orthographicVerticalSize":10,
									"fieldOfView":20,
									"enableHDR":false,
									"nearPlane":0.3,
									"farPlane":5000,
									"viewport":[
										0,
										0,
										1,
										1
									],
									"clearColor":[
										0.5660378,
										0.5660378,
										0.5660378,
										0.6156863
									]
								},
								"components":[
									{
										"type":"Animator",
										"layers":[],
										"cullingMode":0
									}
								],
								"child":[]
							}
						]
					},
					{
						"type":"ShuriKenParticle3D",
						"instanceID":4,
						"props":{
							"name":"bj_ef_xue",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								22.2,
								31.9,
								24.4
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								6.425562,
								6.425566,
								6.425566
							],
							"main":{
								"randomSeed":2.107848E+09,
								"bases":{
									"isPerformanceMode":true,
									"startLifetimeConstant":10,
									"startLifetimeConstantMax":10,
									"startSpeedConstant":-1,
									"startSpeedConstantMax":-1,
									"startSizeType":2,
									"startSizeConstant":0.3,
									"startSizeConstantMin":1,
									"startSizeConstantMax":0.3,
									"maxParticles":40
								},
								"vector3s":{
									"startSizeConstantSeparate":[
										0.3,
										1,
										1
									],
									"startSizeConstantMinSeparate":[
										1,
										1,
										1
									],
									"startSizeConstantMaxSeparate":[
										0.3,
										1,
										1
									]
								}
							},
							"emission":{
								"bases":{
									"enable":true
								}
							},
							"shape":{
								"shapeType":3,
								"bases":{
									"enable":true,
									"x":25.17736,
									"y":46.8849,
									"z":25.99599
								}
							},
							"colorOverLifetime":{
								"bases":{
									"enable":true
								},
								"color":{
									"type":1,
									"gradient":{
										"alphas":[
											{
												"key":0,
												"value":1
											},
											{
												"key":0.3823606,
												"value":1
											},
											{
												"key":0.6617685,
												"value":0.3215686
											},
											{
												"key":1,
												"value":1
											}
										],
										"rgbs":[
											{
												"key":0,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":0.402945,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":0.6470588,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":1,
												"value":[
													1,
													1,
													1
												]
											}
										]
									},
									"gradientMax":{
										"alphas":[
											{
												"key":0,
												"value":1
											},
											{
												"key":0.3823606,
												"value":1
											},
											{
												"key":0.6617685,
												"value":0.3215686
											},
											{
												"key":1,
												"value":1
											}
										],
										"rgbs":[
											{
												"key":0,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":0.402945,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":0.6470588,
												"value":[
													1,
													1,
													1
												]
											},
											{
												"key":1,
												"value":[
													1,
													1,
													1
												]
											}
										]
									}
								}
							},
							"renderer":{
								"resources":{
									"material":"Assets/Scenes/jump/ef/ef_bj.lmat"
								}
							}
						},
						"components":[],
						"child":[]
					},
					{
						"type":"Sprite3D",
						"instanceID":8,
						"props":{
							"name":"bj_sky",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":9,
								"props":{
									"name":"bj",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										26,
										-71,
										52
									],
									"rotation":[
										0,
										0,
										-0.1370561,
										-0.9905633
									],
									"scale":[
										3.13129,
										3.131289,
										3.13129
									],
									"meshPath":"Assets/Scenes/jump/mesh/bj-bj.lm",
									"enableRender":true,
									"receiveShadows":true,
									"castShadow":true,
									"materials":[
										{
											"path":"Assets/Scenes/jump/mat/bj1.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":10,
						"props":{
							"name":"shaoba",
							"active":false,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":11,
								"props":{
									"name":"buff_shaba_fei",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										35,
										0
									],
									"rotation":[
										-0.7071068,
										0,
										0,
										-0.7071068
									],
									"scale":[
										1,
										1,
										1
									],
									"meshPath":"Assets/Scenes/jump/mesh/wujian-buff_shaba_wu11.lm",
									"enableRender":true,
									"receiveShadows":true,
									"castShadow":true,
									"materials":[
										{
											"path":"Assets/Scenes/jump/mat/wujian.lmat"
										}
									]
								},
								"components":[],
								"child":[
									{
										"type":"Sprite3D",
										"instanceID":12,
										"props":{
											"name":"point",
											"active":true,
											"isStatic":false,
											"layer":0,
											"position":[
												0,
												20,
												5
											],
											"rotation":[
												0.7071068,
												0,
												0,
												-0.7071068
											],
											"scale":[
												1,
												1,
												1
											]
										},
										"components":[],
										"child":[]
									}
								]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":13,
								"props":{
									"name":"Smoke_bianshen",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										35,
										9.900001
									],
									"rotation":[
										0.7071068,
										0,
										0,
										-0.7071068
									],
									"scale":[
										15,
										15,
										15
									],
									"main":{
										"randomSeed":0,
										"bases":{
											"isPerformanceMode":true,
											"duration":1,
											"looping":false,
											"startLifetimeType":2,
											"startLifetimeConstant":0.3,
											"startLifetimeConstantMin":0.6,
											"startLifetimeConstantMax":0.3,
											"startSpeedConstant":2,
											"startSpeedConstantMax":2,
											"startSizeType":2,
											"startSizeConstant":0.5,
											"startSizeConstantMin":1.5,
											"startSizeConstantMax":0.5,
											"startRotationType":2,
											"startRotationConstant":6.283185,
											"startRotationConstantMax":6.283185,
											"maxParticles":100
										},
										"vector3s":{
											"startSizeConstantSeparate":[
												0.5,
												1,
												1
											],
											"startSizeConstantMinSeparate":[
												1.5,
												1,
												1
											],
											"startSizeConstantMaxSeparate":[
												0.5,
												1,
												1
											],
											"startRotationConstantSeparate":[
												0,
												0,
												-6.283185
											],
											"startRotationConstantMaxSeparate":[
												0,
												0,
												-6.283185
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":0
										},
										"bursts":[
											{
												"time":0,
												"min":0,
												"max":30
											}
										]
									},
									"shape":{
										"shapeType":1,
										"bases":{
											"enable":true,
											"radius":0.35,
											"x":2,
											"y":2,
											"z":2
										}
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.1705959,
														"value":1
													},
													{
														"key":0.7941253,
														"value":1
													},
													{
														"key":1,
														"value":0
													}
												]
											},
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.1705959,
														"value":1
													},
													{
														"key":0.7941253,
														"value":1
													},
													{
														"key":1,
														"value":0
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.05174518,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.05174518,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.05174518,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0
													},
													{
														"key":0.05174518,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												]
											}
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/CFX2_T_SingleSmoke.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":14,
								"props":{
									"name":"shaba_wei",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0.28,
										34.8,
										1.8
									],
									"rotation":[
										0.9998412,
										0,
										0,
										-0.01782592
									],
									"scale":[
										6.856016,
										6.85602,
										6.85602
									],
									"main":{
										"randomSeed":3.672032E+09,
										"bases":{
											"isPerformanceMode":true,
											"duration":1.5,
											"startLifetimeConstant":1.2,
											"startLifetimeConstantMax":1.2,
											"startSpeedConstant":4.5,
											"startSpeedConstantMax":4.5,
											"startSizeType":2,
											"startSizeConstant":1.5,
											"startSizeConstantMin":0.2,
											"startSizeConstantMax":1.5,
											"startRotationConstant":3.141593,
											"startRotationConstantMax":3.141593,
											"simulationSpeed":5.5,
											"maxParticles":50
										},
										"vector3s":{
											"startSizeConstantSeparate":[
												1.5,
												1,
												1
											],
											"startSizeConstantMinSeparate":[
												0.2,
												1,
												1
											],
											"startSizeConstantMaxSeparate":[
												1.5,
												1,
												1
											],
											"startRotationConstantSeparate":[
												0,
												0,
												-3.141593
											],
											"startRotationConstantMaxSeparate":[
												0,
												0,
												-3.141593
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":20
										}
									},
									"shape":{
										"shapeType":2,
										"bases":{
											"enable":true,
											"radius":0.6,
											"angle":0.05061455,
											"emitType":0
										}
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.627451,
															0
														]
													},
													{
														"key":0.523537,
														"value":[
															0.8584906,
															0.1285662,
															0
														]
													},
													{
														"key":1,
														"value":[
															0,
															0.8509803,
															1
														]
													}
												]
											},
											"gradientMax":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.627451,
															0
														]
													},
													{
														"key":0.523537,
														"value":[
															0.8584906,
															0.1285662,
															0
														]
													},
													{
														"key":1,
														"value":[
															0,
															0.8509803,
															1
														]
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0.9125977
													},
													{
														"key":0.8625488,
														"value":0.353138
													},
													{
														"key":1,
														"value":0.353138
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0.9125977
													},
													{
														"key":0.8625488,
														"value":0.353138
													},
													{
														"key":1,
														"value":0.353138
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0.9125977
													},
													{
														"key":0.8625488,
														"value":0.353138
													},
													{
														"key":1,
														"value":0.353138
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0.9125977
													},
													{
														"key":0.8625488,
														"value":0.353138
													},
													{
														"key":1,
														"value":0.353138
													}
												]
											}
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/star_ADD.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":15,
						"props":{
							"name":"ld",
							"active":false,
							"isStatic":false,
							"layer":0,
							"position":[
								31.8,
								32.8,
								-17
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1.8814,
								1.8814,
								1.8814
							]
						},
						"components":[],
						"child":[
							{
								"type":"ShuriKenParticle3D",
								"instanceID":16,
								"props":{
									"name":"ld",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0.7071068,
										0,
										0,
										-0.7071068
									],
									"scale":[
										12.66,
										12.66,
										12.66
									],
									"main":{
										"randomSeed":4.21347E+09,
										"bases":{
											"isPerformanceMode":true,
											"duration":1,
											"startLifetimeConstant":0.5,
											"startLifetimeConstantMax":0.5,
											"startSpeedConstant":0,
											"startSpeedConstantMax":0,
											"startSizeType":2,
											"startSizeConstant":4.5,
											"startSizeConstantMin":2.5,
											"startSizeConstantMax":4.5,
											"startRotationType":2,
											"startRotationConstant":6.283185,
											"startRotationConstantMax":6.283185,
											"simulationSpeed":2,
											"scaleMode":0,
											"maxParticles":10
										},
										"vector3s":{
											"startSizeConstantSeparate":[
												4.5,
												1,
												1
											],
											"startSizeConstantMinSeparate":[
												2.5,
												1,
												1
											],
											"startSizeConstantMaxSeparate":[
												4.5,
												1,
												1
											],
											"startRotationConstantSeparate":[
												1,
												-1,
												-6.283185
											],
											"startRotationConstantMaxSeparate":[
												1,
												-1,
												-6.283185
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":0
										},
										"bursts":[
											{
												"time":0,
												"min":0,
												"max":1
											}
										]
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":0.5411765,
														"value":1
													},
													{
														"key":0.9120165,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.5499962,
														"value":[
															1,
															0.8490196,
															0.45
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.7254902,
															0
														]
													}
												]
											},
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":0.5411765,
														"value":1
													},
													{
														"key":0.9120165,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.5499962,
														"value":[
															1,
															0.8490196,
															0.45
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.7254902,
															0
														]
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											}
										}
									},
									"textureSheetAnimation":{
										"bases":{
											"enable":true
										},
										"vector2s":{
											"tiles":[
												3,
												3
											]
										},
										"frame":{
											"type":1,
											"overTime":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":8.9991
													}
												]
											},
											"overTimeMax":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":8.9991
													}
												]
											}
										},
										"startFrame":{
											"type":0
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/nova_3x3_spritesheet.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":17,
								"props":{
									"name":"ld2",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										-0.05963168,
										0.7045879,
										-0.7045879,
										0.0596316
									],
									"scale":[
										10.80063,
										10.80062,
										10.80062
									],
									"main":{
										"randomSeed":3.620397E+09,
										"bases":{
											"isPerformanceMode":true,
											"duration":1,
											"startLifetimeConstant":0.5,
											"startLifetimeConstantMax":0.5,
											"startSpeedConstant":0,
											"startSpeedConstantMax":0,
											"startSizeType":2,
											"startSizeConstant":4.5,
											"startSizeConstantMin":2.5,
											"startSizeConstantMax":4.5,
											"startRotationType":2,
											"startRotationConstant":6.283185,
											"startRotationConstantMax":6.283185,
											"simulationSpeed":3,
											"scaleMode":0,
											"maxParticles":10
										},
										"vector3s":{
											"startSizeConstantSeparate":[
												4.5,
												1,
												1
											],
											"startSizeConstantMinSeparate":[
												2.5,
												1,
												1
											],
											"startSizeConstantMaxSeparate":[
												4.5,
												1,
												1
											],
											"startRotationConstantSeparate":[
												1,
												-1,
												-6.283185
											],
											"startRotationConstantMaxSeparate":[
												1,
												-1,
												-6.283185
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":0
										},
										"bursts":[
											{
												"time":0,
												"min":0,
												"max":1
											}
										]
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":0.5411765,
														"value":1
													},
													{
														"key":0.9120165,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.5499962,
														"value":[
															1,
															0.8490196,
															0.45
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.7254902,
															0
														]
													}
												]
											},
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":0.5411765,
														"value":1
													},
													{
														"key":0.9120165,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.5499962,
														"value":[
															1,
															0.8490196,
															0.45
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.7254902,
															0
														]
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0.68125
													},
													{
														"key":1,
														"value":1
													}
												]
											}
										}
									},
									"textureSheetAnimation":{
										"bases":{
											"enable":true
										},
										"vector2s":{
											"tiles":[
												3,
												3
											]
										},
										"frame":{
											"type":1,
											"overTime":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":8.9991
													}
												]
											},
											"overTimeMax":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":8.9991
													}
												]
											}
										},
										"startFrame":{
											"type":0
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/nova_3x3_spritesheet.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":18,
								"props":{
									"name":"buff_ld",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										1,
										1,
										1
									],
									"meshPath":"Assets/Scenes/jump/mesh/wujian-buff_ld_wu5.lm",
									"enableRender":true,
									"receiveShadows":true,
									"castShadow":true,
									"materials":[
										{
											"path":"Assets/Scenes/jump/mat/wujian.lmat"
										}
									]
								},
								"components":[
									{
										"type":"Animator",
										"layers":[
											{
												"name":"Base Layer",
												"weight":0,
												"blendingMode":0,
												"states":[
													{
														"name":"ld",
														"clipPath":"Assets/Scenes/jump/mesh/ld-ld.lani"
													}
												]
											}
										],
										"cullingMode":0,
										"playOnWake":true
									}
								],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":19,
						"props":{
							"name":"Santa",
							"active":false,
							"isStatic":false,
							"layer":0,
							"position":[
								33.4,
								73.4,
								0
							],
							"rotation":[
								0,
								-0.7071068,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[
							{
								"type":"Animator",
								"layers":[
									{
										"name":"Base Layer",
										"weight":0,
										"blendingMode":0,
										"states":[
											{
												"name":"santa",
												"clipPath":"Assets/Scenes/jump/mesh/santa-santa.lani"
											}
										]
									}
								],
								"cullingMode":0,
								"playOnWake":true
							}
						],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":20,
								"props":{
									"name":"Santa",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										0.8,
										0.8,
										0.8
									],
									"meshPath":"Assets/Scenes/jump/mesh/Santa-Santa.lm",
									"enableRender":true,
									"receiveShadows":true,
									"castShadow":true,
									"materials":[
										{
											"path":"Assets/Scenes/jump/mat/Santa.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":21,
								"props":{
									"name":"wei_r",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										12.4,
										-30.3,
										14
									],
									"rotation":[
										0,
										0.01782765,
										0.9998411,
										0
									],
									"scale":[
										3.996748,
										3.996754,
										3.996752
									],
									"main":{
										"randomSeed":3.398013E+09,
										"bases":{
											"isPerformanceMode":true,
											"duration":1.5,
											"startLifetimeConstant":1,
											"startLifetimeConstantMax":1,
											"startSpeedConstant":4.5,
											"startSpeedConstantMax":4.5,
											"startSizeType":2,
											"startSizeConstantMin":0.3,
											"startRotationConstant":3.141593,
											"startRotationConstantMax":3.141593,
											"simulationSpace":0,
											"simulationSpeed":5,
											"maxParticles":20
										},
										"vector3s":{
											"startSizeConstantMinSeparate":[
												0.3,
												1,
												1
											],
											"startRotationConstantSeparate":[
												0,
												0,
												-3.141593
											],
											"startRotationConstantMaxSeparate":[
												0,
												0,
												-3.141593
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":15
										}
									},
									"shape":{
										"shapeType":2,
										"bases":{
											"enable":true,
											"radius":0.6,
											"angle":0.05061455,
											"emitType":0
										}
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.7106807,
															0
														]
													},
													{
														"key":0.2794079,
														"value":[
															0.8117647,
															0.1198427,
															0
														]
													},
													{
														"key":0.8088197,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													}
												]
											},
											"gradientMax":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.7106807,
															0
														]
													},
													{
														"key":0.2794079,
														"value":[
															0.8117647,
															0.1198427,
															0
														]
													},
													{
														"key":0.8088197,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											}
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/star_ADD.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":22,
								"props":{
									"name":"wei_l",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										-12.4,
										-30.3,
										14
									],
									"rotation":[
										0,
										0.01782765,
										0.9998411,
										0
									],
									"scale":[
										3.996748,
										3.996754,
										3.996752
									],
									"main":{
										"randomSeed":1.108376E+09,
										"bases":{
											"isPerformanceMode":true,
											"duration":1.5,
											"startLifetimeConstant":1,
											"startLifetimeConstantMax":1,
											"startSpeedConstant":4.5,
											"startSpeedConstantMax":4.5,
											"startSizeType":2,
											"startSizeConstantMin":0.3,
											"startRotationConstant":3.141593,
											"startRotationConstantMax":3.141593,
											"simulationSpace":0,
											"simulationSpeed":5,
											"maxParticles":20
										},
										"vector3s":{
											"startSizeConstantMinSeparate":[
												0.3,
												1,
												1
											],
											"startRotationConstantSeparate":[
												0,
												0,
												-3.141593
											],
											"startRotationConstantMaxSeparate":[
												0,
												0,
												-3.141593
											]
										}
									},
									"emission":{
										"bases":{
											"enable":true,
											"emissionRate":15
										}
									},
									"shape":{
										"shapeType":2,
										"bases":{
											"enable":true,
											"radius":0.6,
											"angle":0.05061455,
											"emitType":0
										}
									},
									"colorOverLifetime":{
										"bases":{
											"enable":true
										},
										"color":{
											"type":1,
											"gradient":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.7106807,
															0
														]
													},
													{
														"key":0.2794079,
														"value":[
															0.8117647,
															0.1198427,
															0
														]
													},
													{
														"key":0.8088197,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													}
												]
											},
											"gradientMax":{
												"rgbs":[
													{
														"key":0,
														"value":[
															1,
															0.7106807,
															0
														]
													},
													{
														"key":0.2794079,
														"value":[
															0.8117647,
															0.1198427,
															0
														]
													},
													{
														"key":0.8088197,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													},
													{
														"key":1,
														"value":[
															1,
															0.9931743,
															0.4198113
														]
													}
												]
											}
										}
									},
									"sizeOverLifetime":{
										"bases":{
											"enable":true
										},
										"size":{
											"type":0,
											"gradient":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientX":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientMax":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											},
											"gradientXMax":{
												"sizes":[
													{
														"key":0,
														"value":0.8881226
													},
													{
														"key":0.9857788,
														"value":0.4195747
													},
													{
														"key":1,
														"value":0.4195747
													}
												]
											}
										}
									},
									"renderer":{
										"resources":{
											"material":"Assets/Scenes/jump/ef/star_ADD.lmat"
										}
									}
								},
								"components":[],
								"child":[]
							}
						]
					}
				]
			}
		]
	}
}